### ISSUE TITLE
Request for help with .env file

### ISSUE THREAD

**Issue by HiImKobeAnd** [DanielZ1337/itsdu#5]
I'm trying to run the project with `npm dev`, but I dont know what the two .env keys are and where to find them.
Could you provide comments in the example or explain how to find them in this issue?

The two keys in question:
VITE_ITSLEARNING_STORE_KEY=
VITE_ITSLEARNING_OAUTH_STATE=

**Comment by DanielZ1337** [comment]
VITE_ITSLEARNING_STORE_KEY is used for encryption.
VITE_ITSLEARNING_OAUTH_STATE is used for security purposes when sending the OAUTH login request.

Technically, both can be any value you want. One of the most common ways is: "openssl rand -base64 32".
